import { IsString, IsEnum, IsOptional, IsNumber, IsBoolean, IsDateString, IsArray, Min, Max } from 'class-validator';
import { ScheduleVersionType, WeekType } from '../entities/schedule-version.entity';
import { WorkloadWeekType } from '../entities/workload.entity';

// ==================== Schedule Version DTOs ====================

export class CreateScheduleVersionDto {
    @IsString()
    name: string;

    @IsEnum(ScheduleVersionType)
    @IsOptional()
    type?: ScheduleVersionType = ScheduleVersionType.TEMPLATE;

    @IsEnum(WeekType)
    @IsOptional()
    weekType?: WeekType = WeekType.SINGLE;

    @IsNumber()
    @IsOptional()
    copyFromVersionId?: number;

    @IsDateString()
    @IsOptional()
    startDate?: string;

    @IsDateString()
    @IsOptional()
    endDate?: string;

    @IsNumber()
    @IsOptional()
    @Min(1)
    @Max(31)
    workingDays?: number = 31; // Пн-Пт по умолчанию

    @IsNumber()
    @IsOptional()
    @Min(1)
    @Max(10)
    maxLessonsPerDay?: number = 7;
}

export class UpdateScheduleVersionDto {
    @IsString()
    @IsOptional()
    name?: string;

    @IsDateString()
    @IsOptional()
    startDate?: string;

    @IsDateString()
    @IsOptional()
    endDate?: string;

    @IsNumber()
    @IsOptional()
    workingDays?: number;

    @IsNumber()
    @IsOptional()
    maxLessonsPerDay?: number;
}

export class AutoGenerateDto {
    @IsEnum(['full', 'fill_gaps', 'optimize'])
    @IsOptional()
    mode?: 'full' | 'fill_gaps' | 'optimize' = 'full';

    @IsBoolean()
    @IsOptional()
    respectLocked?: boolean = true;

    @IsNumber()
    @IsOptional()
    maxIterations?: number = 10000;

    @IsNumber()
    @IsOptional()
    timeout?: number = 60; // секунды

    @IsOptional()
    priorities?: {
        minimizeWindows: number;
        teacherPreferences: number;
        roomPreferences: number;
        evenDistribution: number;
    };
}

// ==================== Lesson DTOs ====================

export class CreateLessonDto {
    @IsNumber()
    workloadId: number;

    @IsNumber()
    @Min(1)
    @Max(7)
    dayOfWeek: number;

    @IsNumber()
    @Min(1)
    @Max(10)
    lessonNumber: number;

    @IsEnum(WorkloadWeekType)
    @IsOptional()
    weekType?: WorkloadWeekType = WorkloadWeekType.BOTH;

    @IsNumber()
    @IsOptional()
    roomId?: number;
}

export class UpdateLessonDto {
    @IsNumber()
    @IsOptional()
    roomId?: number;

    @IsBoolean()
    @IsOptional()
    isLocked?: boolean;
}

export class MoveLessonDto {
    @IsNumber()
    @Min(1)
    @Max(7)
    dayOfWeek: number;

    @IsNumber()
    @Min(1)
    @Max(10)
    lessonNumber: number;

    @IsEnum(WorkloadWeekType)
    @IsOptional()
    weekType?: WorkloadWeekType;

    @IsNumber()
    @IsOptional()
    roomId?: number;
}

export class CheckPlacementDto {
    @IsNumber()
    workloadId: number;

    @IsNumber()
    @Min(1)
    @Max(7)
    dayOfWeek: number;

    @IsNumber()
    @Min(1)
    @Max(10)
    lessonNumber: number;

    @IsEnum(WorkloadWeekType)
    @IsOptional()
    weekType?: WorkloadWeekType;

    @IsNumber()
    @IsOptional()
    roomId?: number;

    @IsNumber()
    @IsOptional()
    excludeLessonId?: number;
}

// ==================== Workload DTOs ====================

export class CreateWorkloadDto {
    @IsNumber()
    classId: number;

    @IsNumber()
    @IsOptional()
    groupId?: number;

    @IsNumber()
    subjectId: number;

    @IsNumber()
    teacherId: number;

    @IsNumber()
    @IsOptional()
    roomId?: number;

    @IsNumber()
    @IsOptional()
    lessonTypeId?: number;

    @IsNumber()
    @Min(1)
    @Max(20)
    hoursPerWeek: number;

    @IsEnum(WorkloadWeekType)
    @IsOptional()
    weekType?: WorkloadWeekType = WorkloadWeekType.BOTH;

    @IsNumber()
    @IsOptional()
    difficulty?: number;

    @IsArray()
    @IsOptional()
    additionalClassIds?: number[];

    @IsArray()
    @IsOptional()
    additionalTeacherIds?: number[];

    @IsString()
    @IsOptional()
    notes?: string;
}

export class UpdateWorkloadDto {
    @IsNumber()
    @IsOptional()
    groupId?: number;

    @IsNumber()
    @IsOptional()
    teacherId?: number;

    @IsNumber()
    @IsOptional()
    roomId?: number;

    @IsNumber()
    @IsOptional()
    hoursPerWeek?: number;

    @IsEnum(WorkloadWeekType)
    @IsOptional()
    weekType?: WorkloadWeekType;

    @IsString()
    @IsOptional()
    notes?: string;
}

// ==================== Substitution DTOs ====================

export class CreateSubstitutionDto {
    @IsNumber()
    lessonId: number;

    @IsDateString()
    date: string;

    @IsNumber()
    @IsOptional()
    newTeacherId?: number;

    @IsNumber()
    @IsOptional()
    newRoomId?: number;

    @IsNumber()
    @IsOptional()
    newSubjectId?: number;

    @IsBoolean()
    @IsOptional()
    isCancelled?: boolean = false;

    @IsString()
    @IsOptional()
    reason?: string;
}

// ==================== Reference DTOs ====================

export class CreateClassDto {
    @IsString()
    name: string;

    @IsNumber()
    @Min(1)
    @Max(11)
    gradeLevel: number;

    @IsNumber()
    @IsOptional()
    studentsCount?: number = 25;

    @IsNumber()
    @IsOptional()
    maxLessonsPerDay?: number;

    @IsString()
    @IsOptional()
    color?: string = '#2196F3';
}

export class CreateTeacherDto {
    @IsString()
    fullName: string;

    @IsString()
    shortName: string;

    @IsString()
    @IsOptional()
    email?: string;

    @IsString()
    @IsOptional()
    phone?: string;

    @IsString()
    @IsOptional()
    color?: string = '#4CAF50';

    @IsArray()
    @IsOptional()
    subjectIds?: number[];
}

export class CreateSubjectDto {
    @IsString()
    name: string;

    @IsString()
    shortName: string;

    @IsString()
    @IsOptional()
    color?: string = '#FF9800';

    @IsString()
    @IsOptional()
    sanpinCategory?: string;

    @IsNumber()
    @IsOptional()
    @Min(1)
    @Max(13)
    difficulty?: number = 5;
}

export class CreateRoomDto {
    @IsString()
    name: string;

    @IsNumber()
    @IsOptional()
    capacity?: number = 30;

    @IsNumber()
    @IsOptional()
    floor?: number;

    @IsString()
    @IsOptional()
    type?: string = 'regular';

    @IsArray()
    @IsOptional()
    equipment?: string[];
}

export class CreateBellScheduleDto {
    @IsNumber()
    @Min(1)
    @Max(10)
    lessonNumber: number;

    @IsString()
    startTime: string; // HH:MM

    @IsString()
    endTime: string; // HH:MM

    @IsNumber()
    @IsOptional()
    breakAfter?: number = 10;

    @IsString()
    @IsOptional()
    name?: string;
}
