import {
    Controller,
    Get,
    Post,
    Put,
    Delete,
    Body,
    Param,
    Query,
    UseGuards,
    Request,
    Res,
    ParseIntPipe,
    HttpStatus,
    HttpCode,
} from '@nestjs/common';
import type { Response } from 'express';
import { SchoolAuthGuard } from '../../../common/guards/school-auth.guard';
import { ScheduleVersionsService } from '../services/schedule-versions.service';
import { ScheduleSolverService } from '../solver/schedule-solver.service';
import { ScheduleValidatorService } from '../services/schedule-validator.service';
import { ScheduleExportService } from '../services/schedule-export.service';
import {
    CreateScheduleVersionDto,
    UpdateScheduleVersionDto,
    AutoGenerateDto,
} from '../dto/schedule.dto';

@Controller('schedule/versions')
@UseGuards(SchoolAuthGuard)
export class ScheduleVersionsController {
    constructor(
        private versionsService: ScheduleVersionsService,
        private solverService: ScheduleSolverService,
        private validatorService: ScheduleValidatorService,
        private exportService: ScheduleExportService,
    ) {}

    /**
     * Получить список версий расписания
     */
    @Get()
    async findAll(@Request() req) {
        return this.versionsService.findAll(req.user.schoolId);
    }

    /**
     * Получить версию с полными данными расписания
     */
    @Get(':id')
    async findOne(
        @Param('id', ParseIntPipe) id: number,
        @Request() req,
    ) {
        return this.versionsService.findOneWithSchedule(id, req.user.schoolId);
    }

    /**
     * Создать новую версию расписания
     */
    @Post()
    async create(
        @Body() dto: CreateScheduleVersionDto,
        @Request() req,
    ) {
        return this.versionsService.create(dto, req.user.schoolId);
    }

    /**
     * Обновить версию расписания
     */
    @Put(':id')
    async update(
        @Param('id', ParseIntPipe) id: number,
        @Body() dto: UpdateScheduleVersionDto,
        @Request() req,
    ) {
        return this.versionsService.update(id, dto, req.user.schoolId);
    }

    /**
     * Удалить версию расписания
     */
    @Delete(':id')
    @HttpCode(HttpStatus.NO_CONTENT)
    async remove(
        @Param('id', ParseIntPipe) id: number,
        @Request() req,
    ) {
        await this.versionsService.remove(id, req.user.schoolId);
    }

    /**
     * Копировать версию расписания
     */
    @Post(':id/copy')
    async copy(
        @Param('id', ParseIntPipe) id: number,
        @Body('name') name: string,
        @Request() req,
    ) {
        return this.versionsService.copy(id, name, req.user.schoolId);
    }

    /**
     * Активировать версию расписания
     */
    @Post(':id/activate')
    async activate(
        @Param('id', ParseIntPipe) id: number,
        @Request() req,
    ) {
        return this.versionsService.activate(id, req.user.schoolId);
    }

    /**
     * Опубликовать версию расписания
     */
    @Post(':id/publish')
    async publish(
        @Param('id', ParseIntPipe) id: number,
        @Request() req,
    ) {
        return this.versionsService.publish(id, req.user.schoolId);
    }

    /**
     * Валидация расписания
     */
    @Post(':id/validate')
    async validate(
        @Param('id', ParseIntPipe) id: number,
        @Request() req,
    ) {
        return this.validatorService.validateVersion(id, req.user.schoolId);
    }

    /**
     * Автоматическое составление расписания
     */
    @Post(':id/auto-generate')
    async autoGenerate(
        @Param('id', ParseIntPipe) id: number,
        @Body() dto: AutoGenerateDto,
        @Request() req,
    ) {
        // Проверяем права доступа
        await this.versionsService.checkAccess(id, req.user.schoolId);

        return this.solverService.solve(id, {
            mode: dto.mode || 'full',
            respectLocked: dto.respectLocked ?? true,
            maxIterations: dto.maxIterations || 10000,
            timeoutMs: (dto.timeout || 60) * 1000,
            priorities: dto.priorities || {
                minimizeWindows: 8,
                teacherPreferences: 5,
                roomPreferences: 3,
                evenDistribution: 7,
            },
        });
    }

    /**
     * Экспорт расписания
     */
    @Get(':id/export')
    async export(
        @Param('id', ParseIntPipe) id: number,
        @Query('format') format: 'xlsx' | 'pdf' | 'html',
        @Query('view') view: 'class' | 'teacher' | 'room',
        @Query('ids') ids: string,
        @Query('weekType') weekType: 'odd' | 'even',
        @Request() req,
        @Res() res: Response,
    ) {
        const parsedIds = ids ? ids.split(',').map(Number) : undefined;
        const fmt = format || 'xlsx';

        const buffer = await this.exportService.export(id, req.user.schoolId, {
            format: fmt,
            view: view || 'class',
            ids: parsedIds,
            weekType,
        });

        const date = new Date().toISOString().split('T')[0];

        if (fmt === 'xlsx') {
            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            res.setHeader('Content-Disposition', `attachment; filename="schedule_${date}.xlsx"`);
        } else if (fmt === 'html') {
            res.setHeader('Content-Type', 'text/html; charset=utf-8');
            res.setHeader('Content-Disposition', `attachment; filename="schedule_${date}.html"`);
        } else {
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', `attachment; filename="schedule_${date}.pdf"`);
        }

        res.send(buffer);
    }

    /**
     * Получить расписание по классам (для отображения)
     */
    @Get(':id/by-class')
    async getByClass(
        @Param('id', ParseIntPipe) id: number,
        @Query('classId') classId: string,
        @Request() req,
    ) {
        return this.versionsService.getScheduleByClass(
            id,
            req.user.schoolId,
            classId ? Number(classId) : undefined,
        );
    }

    /**
     * Получить расписание по учителям
     */
    @Get(':id/by-teacher')
    async getByTeacher(
        @Param('id', ParseIntPipe) id: number,
        @Query('teacherId') teacherId: string,
        @Request() req,
    ) {
        return this.versionsService.getScheduleByTeacher(
            id,
            req.user.schoolId,
            teacherId ? Number(teacherId) : undefined,
        );
    }

    /**
     * Получить расписание по кабинетам
     */
    @Get(':id/by-room')
    async getByRoom(
        @Param('id', ParseIntPipe) id: number,
        @Query('roomId') roomId: string,
        @Request() req,
    ) {
        return this.versionsService.getScheduleByRoom(
            id,
            req.user.schoolId,
            roomId ? Number(roomId) : undefined,
        );
    }

    /**
     * Получить конфликты расписания
     */
    @Get(':id/conflicts')
    async getConflicts(
        @Param('id', ParseIntPipe) id: number,
        @Query('type') type: 'hard' | 'soft',
        @Query('category') category: string,
        @Request() req,
    ) {
        return this.versionsService.getConflicts(id, req.user.schoolId, {
            type,
            category,
        });
    }

    /**
     * Получить статистику расписания
     */
    @Get(':id/statistics')
    async getStatistics(
        @Param('id', ParseIntPipe) id: number,
        @Request() req,
    ) {
        return this.versionsService.getStatistics(id, req.user.schoolId);
    }
}
